/**
 * Generates src/icons.ts from the Tabler Icons package: pnpm icons
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// The exports map of the package hides its package.json: read from the install directory
const tablerDir = fileURLToPath(new URL("../node_modules/@tabler/icons/", import.meta.url));
const tablerVersion = JSON.parse(readFileSync(`${tablerDir}package.json`, "utf8")).version;

/** State of the widget → Tabler icon */
const ICONS = {
	checkbox: [
		"outline",
		"square",
		"Unchecked box (idle)",
	],
	spinner: [
		"outline",
		"loader-2",
		"Spinner, rotated by the CSS (verifying)",
	],
	checked: [
		"filled",
		"square-check",
		"Checked box (verified)",
	],
	expired: [
		"outline",
		"refresh",
		"Expired, click again",
	],
	error: [
		"outline",
		"alert-triangle",
		"Error, click to retry",
	],
	logo: [
		"outline",
		"shield-check",
		"Logo on the right",
	],
};

/**
 * One-line SVG: no Tabler classes, no fixed size (the CSS sizes it), no invisible bounding box path, hidden from
 * assistive technologies (the widget has its own labels)
 * @param {string} svg
 * @returns {string}
 */
function clean(svg) {
	return svg
		.replace(/\s+/g, " ")
		.replace(/\s(?:width|height|class)="[^"]*"/g, "")
		.replace(/<path stroke="none" d="M0 0h24v24H0z" fill="none" ?\/>/, "")
		.replace(/<svg /, '<svg aria-hidden="true" focusable="false" ')
		.replace(/ ?\/>/g, "/>")
		.replace(/>\s+</g, "><")
		.replace(/\s+>/g, ">")
		.trim();
}

const fields = Object.entries(ICONS).map(([key, [style, name, doc]]) => {
	const svg = clean(readFileSync(`${tablerDir}icons/${style}/${name}.svg`, "utf8"));
	return {
		key,
		name: `${name}${style === "filled" ? " (filled)" : ""}`,
		doc,
		svg,
	};
});

const source = `// Generated by scripts/icons.mjs from @tabler/icons ${tablerVersion} (https://tabler.io/icons): do not edit.
// Tabler Icons: MIT License, Copyright (c) 2020-2026 Paweł Kuna

/**
 * SVG markup of the icons of the widget, inserted as HTML: only pass trusted markup
 */
export interface KnCaptchaIcons {
${fields.map(({ key, doc }) => `\t/** ${doc}, empty string for none */\n\t${key}: string;`).join("\n")}
}

export const tablerIcons: Readonly<KnCaptchaIcons> = {
${fields.map(({ key, name, svg }) => `\t// ${name}\n\t${key}: '${svg}',`).join("\n")}
};
`;

writeFileSync(new URL("../src/icons.ts", import.meta.url), source);
console.log(`src/icons.ts: ${fields.length} icons from @tabler/icons ${tablerVersion}`);
